name: CI
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint:
    name: eslint
    run: echo 'hello world'
   #Lint任务
  UnitTest: 
  # 单元测试任务
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install modules
      run: pnpm install
    - name: Run Test
      run: pnpm run test:run